---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ""
    networking.gke.io/managed-certificates: argocd-tls
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: argocd
    servicePort: 80
