apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: http
    port: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: oshou/awesome-music-api:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 1.1.1.1