apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: oshou/awesome-music-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DRIVER
              value: mysql
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: work
            - name: DB_OPTION
              value: "charset=utf8&parseTime=True&loc=Asia%2FTokyo"
      imagePullSecrets:
        - name: regcred
