apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: http
      port: 3000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: oshou/awesome-music-front:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_HOST
              value: localhost:8080
      imagePullSecrets:
        - name: regcred
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
