apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-front
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: front
              servicePort: 3000
