---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - application/argocd.yaml
  - managed-certificate.yaml
  - ingress.yaml
  - backend-config.yaml
