apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api
          image: oshou/awesome-music-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DRIVER
              value: "$(DB_DRIVER)"
            - name: DB_HOST
              value: "$(DB_HOST)"
            - name: DB_PORT
              value: "$(DB_PORT)"
            - name: DB_PASSWORD
              value: "$(DB_PASSWORD)"
            - name: DB_NAME
              value: "$(DB_NAME)"
            - name: DB_OPTION
              value: "$(DB_OPTION)"
